import content from "@/content/poc.ar.json";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Download, FileCheck2, Printer } from "lucide-react";
import { FormEvent } from "react";
import { useRoute } from "wouter";

export default function Contract() {
  const [, params] = useRoute("/contract/:token"); const token = params?.token ?? ""; const order = trpc.poc.getOrder.useQuery({ token }, { enabled: Boolean(token) }); const contract = trpc.poc.getContract.useQuery({ token }, { enabled: Boolean(token), retry: false }); const create = trpc.poc.createContract.useMutation({ onSuccess: () => void contract.refetch() });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ token, details: { customerName: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), taxCard: String(form.get("taxCard") ?? ""), nationalId: String(form.get("nationalId") ?? ""), commercialRegister: String(form.get("commercialRegister") ?? ""), address: String(form.get("address") ?? "") } }); };
  const download = () => { if (!contract.data) return; const blob = new Blob([contract.data.html], { type: "text/html;charset=utf-8" }); const href = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = href; a.download = `${contract.data.contractNumber}.html`; a.click(); URL.revokeObjectURL(href); };
  if (order.isLoading || contract.isLoading) return <div className="grid min-h-screen place-items-center">جارٍ فتح بيانات العقد…</div>;
  if (order.error || !order.data) return <div className="grid min-h-screen place-items-center p-6 text-center">تعذر العثور على الطلب. ارجع إلى صفحة الدفع التجريبي وافتح رابط العقد من جديد.</div>;
  if (order.data.status !== "PAID_DEMO") return <div className="grid min-h-screen place-items-center p-6 text-center">العقد متاح بعد اعتماد الدفع التجريبي فقط.</div>;
  if (contract.error) return <div className="grid min-h-screen place-items-center p-6 text-center">تعذر فتح العقد الآن. أعد المحاولة بعد لحظات.</div>;
  if (contract.data) return <div className="min-h-screen bg-[#ECECF7] p-5 md:p-10"><div className="mx-auto max-w-3xl rounded-[2rem] bg-white p-8 text-center shadow-[0_30px_80px_-35px_#141651]"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#ECECF7] text-[#4046B5]"><FileCheck2 className="h-9 w-9"/></span><p className="mt-7 text-sm font-bold text-[#4046B5]">{content.contract.created}</p><h1 className="mt-2 font-[Inter] text-2xl font-extrabold" dir="ltr">{contract.data.contractNumber}</h1><p className="mt-5 leading-8 text-[#5b5c72]">تم حفظ نسخة HTML عرضية مع checksum داخلي. يمكنك طباعتها أو تنزيلها لمراجعة شكل المخرج.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button onClick={() => window.open(URL.createObjectURL(new Blob([contract.data?.html ?? ""], { type: "text/html" })), "_blank") } className="rounded-xl bg-[#4046B5]"><Printer className="ml-2 h-4 w-4"/>{content.contract.print}</Button><Button variant="outline" onClick={download} className="rounded-xl"><Download className="ml-2 h-4 w-4"/>{content.contract.download}</Button></div></div></div>;
  return <div className="min-h-screen bg-[#fbfbff] py-10"><div className="container max-w-3xl"><div className="rounded-[2rem] border border-[#4046B5]/10 bg-white p-7 md:p-10"><p className="mof-eyebrow">العقد بعد الدفع التجريبي</p><h1 className="mt-4 text-3xl font-extrabold">{content.contract.title}</h1><p className="mt-4 leading-8 text-[#5b5c72]">{content.contract.body}</p><form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2"><div className="grid gap-2 sm:col-span-2"><Label htmlFor="contract-name">{content.checkout.name}</Label><Input id="contract-name" name="name" defaultValue={order.data.customerName} required/></div><div className="grid gap-2"><Label htmlFor="contract-email">{content.checkout.email}</Label><Input id="contract-email" name="email" defaultValue="" type="email" required dir="ltr"/></div><div className="grid gap-2"><Label htmlFor="contract-phone">{content.checkout.phone}</Label><Input id="contract-phone" name="phone" type="tel" required dir="ltr"/></div><div className="grid gap-2"><Label htmlFor="tax-card">{content.contract.taxCard}</Label><Input id="tax-card" name="taxCard"/></div><div className="grid gap-2"><Label htmlFor="national-id">{content.contract.nationalId}</Label><Input id="national-id" name="nationalId"/></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="commercial">{content.contract.commercialRegister}</Label><Input id="commercial" name="commercialRegister"/></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="address">{content.contract.address}</Label><Textarea id="address" name="address"/></div><Button type="submit" disabled={create.isPending} className="sm:col-span-2 h-13 rounded-xl bg-[#4046B5]">{content.contract.create}</Button>{create.error && <p className="sm:col-span-2 text-sm text-destructive">{create.error.message}</p>}</form></div></div></div>;
}
