import core from "@/content/poc.ar.json";
import sales from "@/content/sales.ar.json";
import { getPocContext, usePocTracking } from "@/hooks/usePocTracking";
import { ADDONS, formatEgp, getPlansForPersona, isCampaignActive, PROMO, type Persona } from "@shared/poc";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ChevronDown, Check, Clock3, FileDown, MessageCircle, MonitorSmartphone, ShieldCheck, Sparkles, UsersRound, X, Zap } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "wouter";

type Consent = { analytics: boolean; marketing: boolean };
const WHATSAPP_URL = "https://wa.me/201000000000?text=" + encodeURIComponent("مرحبًا، أريد مساعدة لاختيار باقة موفوتر المناسبة.");

function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
function readConsent(): Consent | null { try { return JSON.parse(localStorage.getItem("mof_consent") ?? "null"); } catch { return null; } }
function timeLeft(now: number) { const value = Math.max(0, new Date(PROMO.deadlineIso).getTime() - now); return `${Math.floor(value / 86400000)} يوم · ${String(Math.floor((value % 86400000) / 3600000)).padStart(2, "0")}:${String(Math.floor((value % 3600000) / 60000)).padStart(2, "0")}:${String(Math.floor((value % 60000) / 1000)).padStart(2, "0")}`; }

export default function Home() {
  const [, setLocation] = useLocation();
  const track = usePocTracking();
  const trackRef = useRef(track); trackRef.current = track;
  const [persona, setPersona] = useState<Persona>("firm");
  const [gateOpen, setGateOpen] = useState(false);
  const [initialized, setInitialized] = useState(false);
  const [offerDismissed, setOfferDismissed] = useState(false);
  const [now, setNow] = useState(() => Date.now());
  const [selectedPlanSku, setSelectedPlanSku] = useState("professional");
  const [selectedAddons, setSelectedAddons] = useState<string[]>([]);
  const [consent, setConsent] = useState<Consent | null>(null);
  const [exitOpen, setExitOpen] = useState(false);
  const [leadSent, setLeadSent] = useState(false);
  const plans = useMemo(() => getPlansForPersona(persona), [persona]);
  const selectedPlan = plans.find(plan => plan.sku === selectedPlanSku) ?? plans[0];
  const personaCopy = sales[persona];

  useEffect(() => {
    const queryPersona = new URLSearchParams(window.location.search).get("p") as Persona | null;
    const savedPersona = localStorage.getItem("mof_persona") as Persona | null;
    const resolved = queryPersona === "firm" || queryPersona === "company" ? queryPersona : savedPersona;
    if (resolved) { setPersona(resolved); setSelectedPlanSku(getPlansForPersona(resolved).find(plan => plan.featured)?.sku ?? getPlansForPersona(resolved)[0].sku); trackRef.current("persona_resolved", { persona: resolved, uiContext: queryPersona ? "utm" : "storage" }); }
    else { setGateOpen(true); trackRef.current("persona_gate_shown", { uiContext: "first_visit" }); }
    setConsent(readConsent()); setInitialized(true); trackRef.current("page_view", { persona: resolved ?? "firm", uiContext: "landing" });
  }, []);

  useEffect(() => { const interval = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(interval); }, []);
  useEffect(() => {
    if (!initialized || !consent) return;
    const onExit = (event: MouseEvent) => {
      const eligible = window.scrollY > window.innerHeight * .65 || Date.now() - Number(sessionStorage.getItem("mof_visit_started") ?? Date.now()) > 40000;
      if (event.clientY < 4 && eligible && !sessionStorage.getItem("mof_conversion_blocked") && !localStorage.getItem("mof_exit_seen") && !gateOpen) {
        localStorage.setItem("mof_exit_seen", "1"); setExitOpen(true); trackRef.current("exit_intent_shown", { persona, uiContext: "exit_desktop" });
      }
    };
    if (!sessionStorage.getItem("mof_visit_started")) sessionStorage.setItem("mof_visit_started", String(Date.now()));
    document.addEventListener("mouseout", onExit); return () => document.removeEventListener("mouseout", onExit);
  }, [consent, gateOpen, initialized, persona]);

  const choosePersona = (value: Persona, context: string) => {
    const first = getPlansForPersona(value).find(plan => plan.featured) ?? getPlansForPersona(value)[0];
    localStorage.setItem("mof_persona", value); setPersona(value); setSelectedPlanSku(first.sku); setSelectedAddons([]); setGateOpen(false);
    track("persona_selected", { persona: value, uiContext: context });
  };
  const selectPlan = (sku: string) => { setSelectedPlanSku(sku); setSelectedAddons([]); track("plan_selected", { persona, uiContext: "pricing_card", properties: { plan_sku: sku } }); };
  const toggleAddon = (sku: string) => { setSelectedAddons(value => value.includes(sku) ? value.filter(item => item !== sku) : [...value, sku]); track("addon_toggled", { persona, uiContext: "upsell", properties: { addon_sku: sku } }); };
  const continueToCheckout = () => { if (!selectedPlan) return; sessionStorage.setItem("mof_selected_plan", selectedPlan.sku); sessionStorage.setItem("mof_selected_addons", JSON.stringify(selectedAddons)); track("checkout_started", { persona, uiContext: "upsell_cta", properties: { plan_sku: selectedPlan.sku, addons: selectedAddons } }); setLocation(`/checkout?plan=${selectedPlan.sku}&persona=${persona}&addons=${selectedAddons.join(",")}`); };
  const whatsapp = (placement: string) => { sessionStorage.setItem("mof_conversion_blocked", "whatsapp"); track("whatsapp_cta_clicked", { persona, uiContext: placement }); window.open(WHATSAPP_URL, "_blank", "noopener,noreferrer"); };
  const saveConsent = (value: Consent) => { localStorage.setItem("mof_consent", JSON.stringify(value)); setConsent(value); track("consent_updated", { persona, uiContext: "cookie" }); };
  const submitGuide = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLeadSent(true); sessionStorage.setItem("mof_conversion_blocked", "lead"); track("lead_submitted", { persona, uiContext: "guide" }); };
  const activeCampaign = isCampaignActive(new Date(now));

  return <div className="min-h-screen overflow-x-hidden bg-[#fbfbff] text-[#090A20]">
    {activeCampaign && !offerDismissed && <div className="relative z-50 border-b border-[#777ce0]/20 bg-[#0B0B22] text-white"><div className="container flex min-h-11 flex-wrap items-center justify-center gap-x-4 gap-y-1 py-2 text-center text-xs md:text-sm"><span className="font-bold text-[#d7d8ff]">{sales.promo.label}</span><span className="text-white/80">{sales.promo.title}</span><span dir="ltr" className="rounded-md bg-white/10 px-2 py-0.5 font-[Inter] text-[11px] tabular-nums">{timeLeft(now)}</span><button onClick={() => { track("promo_banner_clicked", { persona, uiContext: "top_banner" }); scrollToId("pricing"); }} className="font-extrabold text-[#c5c8ff] hover:text-white">{sales.promo.cta}</button><button aria-label="إغلاق العرض" onClick={() => { setOfferDismissed(true); track("promo_banner_dismissed", { persona, uiContext: "top_banner" }); }}><X className="h-4 w-4"/></button></div></div>}

    <header className="sticky top-0 z-40 border-b border-[#4046B5]/10 bg-[#fbfbff]/95 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between gap-4"><button onClick={() => setGateOpen(true)} className="group flex items-center gap-3 text-right"><img src="/manus-storage/mofawtar-wordmark_74721d27.png" alt="مفوتر" className="h-10 w-auto"/><span className="hidden border-r border-[#4046B5]/15 pr-3 text-xs font-bold text-[#585972] sm:block">{persona === "firm" ? "تجربة مكاتب المحاسبة" : "تجربة المحاسب والشركة"}<span className="mt-0.5 block text-[#4046B5] group-hover:underline">تغيير</span></span></button><nav className="hidden items-center gap-7 text-sm font-bold lg:flex"><button onClick={() => scrollToId("how-it-works")} className="hover:text-[#4046B5]">كيف تناسب عملك؟</button><button onClick={() => scrollToId("pricing")} className="hover:text-[#4046B5]">الباقات</button><button onClick={() => scrollToId("upsell")} className="hover:text-[#4046B5]">الإضافات</button></nav><Button onClick={() => scrollToId("pricing")} className="rounded-xl bg-[#4046B5] px-5 font-bold hover:bg-[#343aa0]">اختَر باقتك</Button></div></header>

    <main>
      <section className="mof-grid relative overflow-hidden"><div className="container grid min-h-[660px] items-center gap-10 py-14 lg:grid-cols-[1.08fr_.92fr] lg:py-20"><div className="relative z-10"><div className="inline-flex items-center gap-2 rounded-full border border-[#4046B5]/15 bg-white px-3 py-1.5 text-xs font-bold text-[#4046B5]"><Sparkles className="h-4 w-4"/>{personaCopy.eyebrow}</div><h1 className="mt-5 max-w-3xl text-4xl font-extrabold leading-[1.22] tracking-tight md:text-6xl">{personaCopy.title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#54556d] md:text-lg">{personaCopy.body}</p><div className="mt-7 grid max-w-xl gap-3">{personaCopy.proof.map(item => <div key={item} className="flex items-center gap-3 text-sm font-bold text-[#33344e]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#EDEEF9] text-[#4046B5]"><Check className="h-4 w-4"/></span>{item}</div>)}</div><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" onClick={() => { track("hero_cta_clicked", { persona, uiContext: "hero_primary" }); scrollToId("pricing"); }} className="h-13 rounded-xl bg-[#4046B5] px-6 text-base hover:bg-[#343aa0]">{personaCopy.primary}</Button><Button size="lg" variant="outline" onClick={() => whatsapp("hero_secondary")} className="h-13 rounded-xl border-[#4046B5]/25 bg-white px-6 text-[#4046B5]"><MessageCircle className="ml-2 h-4 w-4"/>{personaCopy.secondary}</Button></div></div><div className="relative"><div className="absolute -inset-6 rounded-[3rem] bg-[#4046B5]/10 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white bg-white p-3 shadow-[0_35px_85px_-42px_#121342]"><img src="/manus-storage/mofawtar-ledger-hero_28133c0b.png" alt="ملفات وفواتير منظمة داخل واجهة موفوتر" className="aspect-[4/3] w-full rounded-[1.45rem] object-cover"/><div className="absolute bottom-7 right-7 left-7 rounded-2xl border border-white/80 bg-white/95 p-4 shadow-lg backdrop-blur"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EDEEF9] text-[#4046B5]">{persona === "firm" ? <UsersRound className="h-5 w-5"/> : <MonitorSmartphone className="h-5 w-5"/>}</span><div><p className="text-xs font-bold text-[#4046B5]">{persona === "firm" ? "عرض المكتب" : "عرض الشركة"}</p><p className="mt-1 text-sm font-extrabold">{persona === "firm" ? "سعة ملفّات + فريق + متابعة" : "ملف ضريبي + إصدار + نمو منظم"}</p></div></div></div></div></div></div></section>

      <section id="how-it-works" className="border-y border-[#4046B5]/10 bg-white"><div className="container grid gap-4 py-7 md:grid-cols-3"><article className="flex gap-4"><span className="font-[Inter] text-3xl font-extrabold text-[#4046B5]/25">01</span><div><h2 className="font-extrabold">اختَر حسب حجم عملك</h2><p className="mt-1 text-sm leading-6 text-[#606178]">الفرق يبدأ بعدد الملفات والمستخدمين، لا بأسماء مبهمة.</p></div></article><article className="flex gap-4"><span className="font-[Inter] text-3xl font-extrabold text-[#4046B5]/25">02</span><div><h2 className="font-extrabold">أضف ما يحل عائقًا حقيقيًا</h2><p className="mt-1 text-sm leading-6 text-[#606178]">الإصدار أو POS أو مستخدم إضافي، كل إضافة لها سبب واضح.</p></div></article><article className="flex gap-4"><span className="font-[Inter] text-3xl font-extrabold text-[#4046B5]/25">03</span><div><h2 className="font-extrabold">شاهد المبلغ قبل قرارك</h2><p className="mt-1 text-sm leading-6 text-[#606178]">الحساب النهائي والضريبة يظهران في الـCheckout قبل الدفع التجريبي.</p></div></article></div></section>

      <section id="pricing" className="mof-section"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="mof-eyebrow">{sales.pricing.eyebrow}</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">{persona === "firm" ? sales.pricing.firmTitle : sales.pricing.companyTitle}</h2><p className="mt-5 leading-8 text-[#5b5c72]">{sales.pricing.body}</p></div><div className={`mt-12 grid gap-5 ${persona === "firm" ? "md:grid-cols-2 xl:grid-cols-4" : "mx-auto max-w-4xl md:grid-cols-2"}`}>{plans.map(plan => <article key={plan.sku} className={`relative flex min-w-0 flex-col rounded-[2rem] border p-6 shadow-[0_20px_50px_-42px_#4046B5] transition-transform hover:-translate-y-1 ${plan.featured ? "border-[#4046B5] bg-[#F7F7FF] shadow-[0_26px_55px_-34px_#4046B5]" : "border-[#4046B5]/12 bg-white"}`}>
        {plan.badge && <div className="absolute -top-3 right-5 rounded-full bg-[#4046B5] px-3 py-1 text-xs font-bold text-white">{plan.badge}</div>}<p className="text-xs font-bold text-[#4046B5]">{plan.files}</p><h3 className="mt-3 text-2xl font-extrabold">{plan.name}</h3><p className="mt-3 min-h-14 text-sm leading-7 text-[#5a5b71]">{plan.description}</p><div className="mt-6 border-y border-[#4046B5]/10 py-5"><p className="font-[Inter] text-3xl font-extrabold" dir="ltr">{formatEgp(plan.annualPiastres)}</p><p className="mt-1 text-xs text-[#64657a]">{sales.pricing.from}</p></div><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#EDEEF9] p-3"><p className="text-[11px] font-bold text-[#62647d]">السعة</p><p className="mt-1 text-sm font-extrabold text-[#4046B5]">{plan.files}</p></div><div className="rounded-xl bg-[#EDEEF9] p-3"><p className="text-[11px] font-bold text-[#62647d]">الفريق</p><p className="mt-1 text-sm font-extrabold text-[#4046B5]">{plan.users}</p></div></div><p className="mt-5 text-xs font-bold text-[#4046B5]">{sales.pricing.decision}</p><p className="mt-1 min-h-12 text-xs leading-6 text-[#5a5b71]">{plan.decisionCue}</p><ul className="mt-5 space-y-3 border-t border-[#4046B5]/10 pt-5">{plan.features.map(feature => <li key={feature} className="flex items-start gap-2 text-sm leading-6"><Check className="mt-1 h-4 w-4 shrink-0 text-[#4046B5]"/>{feature}</li>)}</ul><Button onClick={() => { selectPlan(plan.sku); scrollToId("upsell"); }} className={`mt-7 rounded-xl ${plan.featured ? "bg-[#4046B5] hover:bg-[#343aa0]" : "bg-[#090A20] hover:bg-[#262642]"}`}>{selectedPlanSku === plan.sku ? "الباقة المختارة" : sales.pricing.select}</Button></article>)}</div></div></section>

      <section id="upsell" className="mof-section bg-[#0B0B22] text-white"><div className="container"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mof-eyebrow text-[#c6c8ff]">{sales.upsell.eyebrow}</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">{sales.upsell.title}</h2><p className="mt-5 leading-8 text-white/70">{sales.upsell.body}</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-bold text-[#c6c8ff]">اختيارك الحالي</p><p className="mt-2 text-xl font-extrabold">{selectedPlan?.name}</p><p className="mt-2 text-sm text-white/65">{selectedPlan?.decisionCue}</p></div></div><div className="grid gap-4">{ADDONS.map(addon => { const included = addon.includedIn?.includes(selectedPlan?.sku ?? ""); const chosen = selectedAddons.includes(addon.sku); return <article key={addon.sku} className={`rounded-3xl border p-5 transition ${included ? "border-[#8e93f4]/35 bg-[#4046B5]/25" : chosen ? "border-[#c5c8ff] bg-white text-[#090A20]" : "border-white/12 bg-white/[.04]"}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${included ? "bg-white/10 text-white" : chosen ? "bg-[#EDEEF9] text-[#4046B5]" : "bg-white/10 text-[#c6c8ff]"}`}><Zap className="h-5 w-5"/></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{addon.name}</h3>{included && <span className="rounded-full bg-[#c6c8ff] px-2 py-0.5 text-[10px] font-bold text-[#0B0B22]">{sales.upsell.included}</span>}</div><p className={`mt-2 text-sm leading-7 ${chosen ? "text-[#5b5c72]" : "text-white/65"}`}>{addon.description}</p><p className={`mt-2 text-xs font-bold ${chosen ? "text-[#4046B5]" : "text-[#c6c8ff]"}`}>{addon.salesCue}</p></div></div><div className="shrink-0 text-right"><p className="font-[Inter] text-lg font-extrabold" dir="ltr">{included ? "متضمن" : `+ ${formatEgp(addon.annualPiastres)}`}</p>{!included && <label className={`mt-3 flex cursor-pointer items-center justify-end gap-2 text-xs font-bold ${chosen ? "text-[#4046B5]" : "text-white"}`}><Checkbox checked={chosen} onCheckedChange={() => toggleAddon(addon.sku)}/>{chosen ? sales.upsell.added : sales.upsell.choose}</label>}</div></div></article>; })}<Button onClick={continueToCheckout} className="mt-2 h-13 rounded-xl bg-white text-[#4046B5] hover:bg-[#EDEEF9]">{sales.upsell.cta}</Button></div></div></div></section>

      <section className="mof-section"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mof-eyebrow">لماذا هذه الباقات؟</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">{sales.why.title}</h2><p className="mt-5 max-w-md leading-8 text-[#5b5c72]">لا نضع مميزات عامة في كل بطاقة. الفرق بين الباقات ظاهر في السعة وعدد المستخدمين والنتيجة التي تخدمها.</p></div><div className="grid gap-3 sm:grid-cols-2">{sales.why[persona].map((item, index) => <article key={item} className="flex gap-4 rounded-2xl border border-[#4046B5]/10 bg-white p-5"><span className="font-[Inter] text-2xl font-extrabold text-[#4046B5]/30">0{index + 1}</span><p className="font-bold leading-7">{item}</p></article>)}</div></div></section>

      <section className="mof-section bg-[#EDEEF9]/60"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="mof-eyebrow">{sales.common.eyebrow}</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">{sales.common.title}</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{sales.common.items.map((item, index) => <article key={item} className="rounded-2xl border border-[#4046B5]/10 bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#EDEEF9] font-[Inter] text-sm font-extrabold text-[#4046B5]">0{index + 1}</span><p className="mt-5 font-extrabold leading-7">{item}</p></article>)}</div></div></section>

      <section className="pb-16"><div className="container"><div className="grid gap-8 overflow-hidden rounded-[2rem] bg-[#4046B5] p-8 text-white md:grid-cols-[1fr_auto] md:p-12"><div><p className="text-xs font-bold tracking-[.18em] text-[#d7d8ff]">دليل بداية منظم</p><h2 className="mt-3 text-3xl font-extrabold">{sales.cta.title}</h2><p className="mt-4 max-w-xl leading-8 text-white/75">{sales.cta.body}</p><form onSubmit={submitGuide} className="mt-6 flex max-w-lg flex-col gap-3 sm:flex-row"><input required type="email" placeholder="بريد العمل الإلكتروني" className="h-12 flex-1 rounded-xl border-0 bg-white px-4 text-sm text-[#090A20] outline-none" dir="ltr"/><Button type="submit" className="h-12 rounded-xl bg-[#090A20] hover:bg-[#232444]">{leadSent ? "تم استلام طلبك" : "أرسل لي الدليل"}</Button></form></div><Button onClick={() => whatsapp("bottom_cta")} variant="outline" className="h-13 self-center rounded-xl border-white/35 bg-white/10 px-6 text-white hover:bg-white hover:text-[#4046B5]"><MessageCircle className="ml-2 h-4 w-4"/>{sales.cta.button}</Button></div></div></section>
    </main>

    <footer className="border-t border-[#4046B5]/10 py-8"><div className="container flex flex-col items-center justify-between gap-4 text-center text-xs text-[#64657a] md:flex-row"><img src="/manus-storage/mofawtar-wordmark_74721d27.png" alt="مفوتر" className="h-8 w-auto"/><p>موفوتر — نموذج إثبات مفهوم لرحلة بيع SaaS.</p><a href="/dashboard" className="font-bold text-[#4046B5]">لوحة المؤشرات</a></div></footer>
    <button onClick={() => whatsapp("floating")} className="fixed bottom-5 left-5 z-40 flex items-center gap-2 rounded-full bg-[#25D366] px-4 py-3 text-sm font-bold text-white shadow-lg transition-transform hover:-translate-y-0.5"><MessageCircle className="h-5 w-5"/>واتساب</button>

    {consent === null && <div className="fixed inset-x-3 bottom-3 z-50 mx-auto max-w-3xl rounded-2xl border border-[#4046B5]/15 bg-white p-5 shadow-[0_25px_70px_-30px_#07081A]"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-extrabold">{core.cookies.title}</p><p className="mt-1 max-w-xl text-xs leading-6 text-[#5b5c72]">{core.cookies.body}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => saveConsent({ analytics: false, marketing: false })}>{core.cookies.reject}</Button><Button size="sm" onClick={() => saveConsent({ analytics: true, marketing: true })}>{core.cookies.accept}</Button></div></div></div>}

    <Dialog open={gateOpen} onOpenChange={open => { if (!open) track("persona_gate_dismissed", { persona, uiContext: "gate" }); setGateOpen(open); }}><DialogContent className="max-w-2xl overflow-hidden rounded-[2rem] border-0 p-0"><div className="bg-[#0B0B22] p-7 text-white"><p className="text-xs font-bold tracking-[.18em] text-[#c6c8ff]">{sales.gate.eyebrow}</p><DialogHeader><DialogTitle className="mt-3 text-3xl text-white">{sales.gate.title}</DialogTitle><DialogDescription className="mt-3 leading-7 text-white/70">{sales.gate.body}</DialogDescription></DialogHeader></div><div className="grid gap-4 p-6 sm:grid-cols-2"><button onClick={() => choosePersona("firm", "gate")} className="rounded-2xl border border-[#4046B5]/15 p-6 text-right transition hover:-translate-y-0.5 hover:border-[#4046B5] hover:bg-[#F7F7FF]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EDEEF9] text-[#4046B5]"><UsersRound className="h-5 w-5"/></span><h3 className="mt-5 text-xl font-extrabold">{sales.gate.firm.title}</h3><p className="mt-2 text-sm leading-7 text-[#5b5c72]">{sales.gate.firm.body}</p></button><button onClick={() => choosePersona("company", "gate")} className="rounded-2xl border border-[#4046B5]/15 p-6 text-right transition hover:-translate-y-0.5 hover:border-[#4046B5] hover:bg-[#F7F7FF]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EDEEF9] text-[#4046B5]"><MonitorSmartphone className="h-5 w-5"/></span><h3 className="mt-5 text-xl font-extrabold">{sales.gate.company.title}</h3><p className="mt-2 text-sm leading-7 text-[#5b5c72]">{sales.gate.company.body}</p></button><button onClick={() => { setGateOpen(false); track("persona_gate_skipped", { persona, uiContext: "gate" }); }} className="sm:col-span-2 text-sm font-bold text-[#64657a] hover:text-[#4046B5]">{sales.gate.skip}</button></div></DialogContent></Dialog>
    <Dialog open={exitOpen} onOpenChange={setExitOpen}><DialogContent className="max-w-md rounded-3xl"><DialogHeader><p className="text-xs font-bold tracking-[.18em] text-[#4046B5]">قبل أن تغادر</p><DialogTitle className="mt-2 text-2xl">هل تفضل بداية أسرع؟</DialogTitle><DialogDescription className="leading-7">أخبرنا بعدد الملفات أو المستخدمين، وسنساعدك في تحديد سعة مناسبة قبل اختيار الباقة.</DialogDescription></DialogHeader><div className="mt-3 flex flex-wrap gap-3"><Button onClick={() => whatsapp("exit_intent")} className="rounded-xl bg-[#4046B5]"><MessageCircle className="ml-2 h-4 w-4"/>تواصل عبر واتساب</Button><Button variant="outline" onClick={() => setExitOpen(false)} className="rounded-xl">أكمل التصفح</Button></div></DialogContent></Dialog>
  </div>;
}
